Add  Interview Data
AY2122S2-CS2103T-T11-3/tp pull request #58
Opened 2022-03-13 14:51 UTC by laughingkid-sg

Fix #38

2022-03-13 18:28 UTC, laughingkid-sg commented
# Added Interview Slot field in Application

## Key Summary
- Created  `InterviewSlot` class
- Interview slot is stored as a `LocalDateTime` value in the `InterviewSlot` class
- Adding a new application will default the value to `LocalDateTime.Max` & the value will default to **_Interview date is not set._**
- Edit command is re-enabled to cater to the adding of the interview time slot
-  Comparison between `InterviewSlot` class compares its `String` value instead of its actual value because when saving to JSON, data of  `LocalDateTime.Max` is truncated
- Input format is `dd-MM-yyyy HH:mm` and display format is `d MMM yyyy HH:mm`

## Usage

### Adding/Replacing interview slot
Command: `edit 1 idt/13-03-2022 13:00`
Feedback: 

> Edited Person: Shopee; Job Title: Software Engineer Intern; Phone: 87438807; Email: hr@shopee.sg; Address: 5 Science Park Dr, #06-40; Interview Slot: 13 Mar 2022 13:00; Tags: [friends]

### Removing interview slot
Command: `edit 1 idt/`
Feedback: 

> Edited Person: Shopee; Job Title: Software Engineer Intern; Phone: 87438807; Email: hr@shopee.sg; Address: 5 Science Park Dr, #06-40; Interview Slot: Interview date is not set.; Tags: [friends]

## Preview
![image](https://user-images.githubusercontent.com/24849568/158073608-d32a568e-b9d0-4193-bfcd-85a494088dad.png)

## Other Updates
- Update `SampleDataUtil` to reflect applications 
- Updated some test case data to reflect applications


## Further improvements
1. Will highlight in GUI that interview date is not set for application depending on tags
2. Additional test cases for InterviewSlot
3. Suggestion to change `idt/` to 'interview/'
4. Update remaining test cases data to reflect application

2022-03-14 00:54 UTC, lchokhoe requested changes
**lchokhoe.png file does not need to be updated, please revert the changes in another commit.**

While you are at it, some of the files had extra lines as well, I commented on them but here's where they are:
1. (main folder) InterviewSlot.java (Line 10 - Line 13)
2. (test folder) CommandParserTestUtil.java (Line 19)
3. (test folder) PersonBuilder.java (Line 31 and Line 40)

Other then that I think all the changes you made LGTM 👍

2022-03-14 00:54 UTC, lchokhoe commented on src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
> +
You can remove this line as well while you are reverting the changes to lchokhoe.png.

2022-03-14 00:54 UTC, lchokhoe commented on src/test/java/seedu/address/testutil/PersonBuilder.java
> +
You can remove this line as well while you are reverting the changes to lchokhoe.png.

2022-03-14 00:54 UTC, lchokhoe commented on src/test/java/seedu/address/testutil/PersonBuilder.java
> +
You can remove this line as well while you are reverting the changes to lchokhoe.png.

2022-03-14 00:54 UTC, lchokhoe commented on src/main/java/seedu/address/model/application/InterviewSlot.java
> +
I think you can clear away these extra lines while you are reverting the changes to lchokhoe.png.

2022-03-14 01:20 UTC, laughingkid-sg commented
> **lchokhoe.png file does not need to be updated, please revert the changes in another commit.**
> 
> While you are at it, some of the files had extra lines as well, I commented on them but here's where they are:
> 
> 1. (main folder) InterviewSlot.java (Line 10 - Line 13)
> 2. (test folder) CommandParserTestUtil.java (Line 19)
> 3. (test folder) PersonBuilder.java (Line 31 and Line 40)
> 
> Other then that I think all the changes you made LGTM 👍

@lchokhoe Image updated as per #59 & remove blank spaces

2022-03-14 01:24 UTC, lchokhoe approved these changes
Nice!

2022-03-14 01:24 UTC, merged